### ISSUE TITLE
[RPI2] [BUG] MGS Graphic Glitch

### ISSUE THREAD

**Issue by nemo93** [libretro/pcsx_rearmed#40] opened 2016-05-14 08:59 UTC
This issue is pretty easy to reproduce. Instead of the white flash which usually opens a cut scene there is a pixel mess with a kind of stroboscopic effect. Really weird. Let me attach a screenshot as it's worth a thousand words I guess. The first time to see this it's right after the lift, after Snake takes his swimsuit off. It appears again just a few seconds later when Snake stares at the Hind-D.

I'm using a RP2, latest Retropie version (3.7 final), this core freshly built (but same behavior with the other rearmed core). Core options all by default/auto. No video enhancement turned on or something. I'm using bios SCPH1001.BIN but it makes no difference as same behavior occurs with any other bioses.

As french I'm playing with the FR version of the game (not the Integral or Special version of the game). Didn't try with another version but I could do so if that helps.

Thanks for your help and assistance.

![54a8b63a-5035-11e5-9423-056e2b85e2f8](https://cloud.githubusercontent.com/assets/8100500/15267446/b57fb48e-19c2-11e6-839a-4c9a78600f42.png)

**Comment by Jimmy-Z** [comment] 2017-01-10 09:42
I can confirm this with:
RetroArch 1.36 Android, armeabi-v7a
PCSX-ReARMed r22 abaa8b9
BIOS: scph5500.bin
MGS Integral (Japan)

It also happens on Vita, pretty sure the most recent nightly.

**Comment by meepingsnesroms** [comment] 2017-01-24 03:01
Does the English version work?

**Comment by Jimmy-Z** [comment] 2017-02-12 15:12
confirmed again with lakka RPi2 Dec 21 2016 git 274b40f, RetroArch 1.3.6, PCSX-ReARMed r22 e7fddd8
BIOS scph5501.bin
MGS (US v1.1) (by English I guess you meant US release, JP Integral also has English)
more screenshots:
![image](https://cloud.githubusercontent.com/assets/85773/22863215/e35fac4c-f176-11e6-9dfd-3248cac4b9f8.png)
![image](https://cloud.githubusercontent.com/assets/85773/22863216/e74efc90-f176-11e6-9f32-0e6e825b978b.png)

**Comment by soulgriever** [comment] 2017-07-19 04:23
Does this glitch occur with NEON enabled?

**Comment by Jimmy-Z** [comment] 2017-07-20 11:07
I think it is, I didn't see an option to turn NEON off?

And at a wild guess this might be related to #103, I mean inaccurate signed/unsigned casting might cause such effects.

**Comment by soulgriever** [comment] 2017-07-20 22:33
https://github.com/RetroPie/RetroPie-Setup/wiki/Playstation-1#enhanced-graphics

It is not enabled by default, try enabling NEON and let me know if it fixes the issue

**Comment by Jimmy-Z** [comment] 2017-07-21 04:34
What are you talking about, NEON is a compile time option, this is just a GPU plugin setting, not choosing GPU plugin.

Anyway I thought double resolution might have some effect on the bug so I tried it, but no, it's still here.

And I tested with dynarec off, turns out that wild guess was wrong.

**Comment by Jimmy-Z** [comment] 2017-09-13 10:13
Tested 09d454e on Android, still there.

**Comment by Jimmy-Z** [comment] 2019-11-01 03:22
I got an PS mini, it has MGS and from what I've heard it's using pcsx-rearmed, I'd hope they fixed this.

**Comment by AnotherLife** [comment] 2019-11-01 13:08
This is a problem with the NEON video plugin, sadly. And the Peops plugin is too slow.

**Comment by Jimmy-Z** [comment] 2020-08-04 06:57
PS mini does not have this issue, I heard it's open source, maybe we can merge that? but I can't find the (supposedly open) source anywhere.

**Comment by gameblabla** [comment] 2021-10-02 01:52
> PS mini does not have this issue, I heard it's open source, maybe we can merge that? but I can't find the (supposedly open) source anywhere.

I would have to seriously look into it but as far as MGS is concerned, i only noticed CDRM hacks in the PS Classic branch and some Link changes for Armored core.

**Comment by gameblabla** [comment] 2021-10-02 03:10
Does that issue still happen ? I looked at the PS Classic fork and as far as MGS is concerned, these are the only hacks they used for it that are relevant :
```c
	} else if (isTitleName(METAL_GEAR_SOLID_DISC_1_EU) ||
			isTitleName(METAL_GEAR_SOLID_DISC_1_JP) ||
			isTitleName(METAL_GEAR_SOLID_DISC_1_US)) {
		if (cdr.Cmd == CdlSetloc &&
				cdr.Param[0] == 0x0 &&
				cdr.Param[1] == 0x2 &&
				cdr.Param[2] == 0x22 &&
				RunBiosLogoFarst == 0) {
			AddIrqQueue(cdr.Cmd, cdReadTime * 400);
			RunBiosLogoFarst = 1;
		} else {
			AddIrqQueue(cdr.Cmd, 0x800);
		}
```
in cdrom.c and cdrWrite1 after cdr.Ctrl |= 0x80;

and this one
```c
static int setTitleAddVram2(){
  int ret = isTitleName(METAL_GEAR_SOLID_DISC_1_EU)
            || isTitleName(METAL_GEAR_SOLID_DISC_1_JP)
            || isTitleName(METAL_GEAR_SOLID_DISC_1_US)
            || isTitleName(METAL_GEAR_SOLID_DISC_2_EU)
            || isTitleName(METAL_GEAR_SOLID_DISC_2_JP)
            || isTitleName(METAL_GEAR_SOLID_DISC_2_US);

  if(GPU_setPatchFlag)
	GPU_setPatchFlag(GPU_PATCH_ADD_VRAM2, ret);
  return ret;
}
```
in misc.c

GPU_PATCH_ADD_VRAM2 is implemented as a hack in gpulib's gpu.c. Either way, i hope we fix it the proper way and not like this.

**Comment by gameblabla** [comment] 2021-10-02 10:20
I tested this on both the Funkey-S and PC (x86_64) and i am unable to get that kind of glitchyness, even on ARM/NEON.
I believe this was fixed somewhere down the line when they did a few NEON related fixes... or it was a GTE issue.
Either way, i'm closing this unless someone here can tell me that it's still broken.

**Comment by gameblabla** [comment] 2021-10-08 11:51
I'm reopening this i guess but yeah, i can't really see it at all on my test devices, including on ARM... Could be android specific i guess or a compiler issue, who knows. (Or an actual glitch)

**Comment by Jimmy-Z** [comment] 2021-10-09 10:04
Just realized android retroarch doesn't support recording, so making a video will be ... a hassle for me since I'm lazy.

I made some more screenshots though.
![Metal Gear Solid - Integral (Japan) (En,Ja) (Disc 1)-211009-174912](https://user-images.githubusercontent.com/85773/136653591-85f8f5f9-0ed3-4a7d-91e1-8eb65e88451e.png)
![Metal Gear Solid - Integral (Japan) (En,Ja) (Disc 1)-211009-174858](https://user-images.githubusercontent.com/85773/136653593-34dca2c2-e344-4148-9e81-cd2a9003993a.png)
![Metal Gear Solid - Integral (Japan) (En,Ja) (Disc 1)-211009-175003](https://user-images.githubusercontent.com/85773/136653596-19efe92f-61d7-49f6-af5a-2a19eda81f84.png)
![Metal Gear Solid - Integral (Japan) (En,Ja) (Disc 1)-211009-174958](https://user-images.githubusercontent.com/85773/136653598-86b17861-0211-45e7-9758-72e0c0e9726a.png)

It's funny though one of the screenshot included the notification overlay.

**Comment by Jimmy-Z** [comment] 2021-10-12 04:41
Yeah, it's NEON, I realized later I could distinguish from the GPU options.

**Comment by notaz** [comment] 2023-10-15 15:52
I tried this on arm32 (r-pi4) and couldn't see any issues in the scenes just after taking the elevator. I'm going to assume this was fixed along with some blending fixes around a year ago or so.

**Closed by notaz** 2023-10-15 15:52 UTC
