### ISSUE TITLE
Stuttering sound on RK3328 aarch64 build

### ISSUE THREAD

**Issue by wn2000** [libretro/pcsx_rearmed#489] opened 2021-01-18 05:15 UTC
I built this core on RK3328 aarch64 Linux. Tried several games, the video seems to be smooth enough, but audio is always choppy. It's like the audio would play for half a second then stop, then play another half second and stop...
The internal FPS shows 30 FPS most of the time, and RetroArch reports 47-52 FPS.
Is it normal for the internal FPS being 30?

Tried building with peops and unai plugin, with threaded video on and off, the audio issue is about the same.

Anyway to improve the audio? The video performance is good enough to be playable. It's just the choppy audio makes it "feel" slow.

**Comment by notaz** [comment] 2022-04-08 21:53
Was probably caused by the lack of dynarec (or Lightrec being very slow) at that time. Assumed to be fixed now, feel free to reopen if it's not.

**Closed by notaz** 2022-04-08 21:53 UTC
