### ISSUE TITLE
[HLE] No sound effects in Herc's Adventures

### ISSUE THREAD

**Issue by Kekun** [libretro/pcsx_rearmed#57] opened 2016-08-28 06:36 UTC
There is no sound effects in Herc's Adventures (US version) with the HLE BIOS, though music plays as intended.

**Comment by hooby3dfx** [comment] 2017-04-02 20:16
looks like duplicate of https://github.com/libretro/pcsx_rearmed/issues/59

**Comment by negativeExponent** [comment] 2021-04-24 23:20
for better compatibility, an official bios should be used

**Comment by gameblabla** [comment] 2021-10-02 01:10
This probably got fixed with my newer HLE changes anyway although i would have to check this... (Digimon World still has missing sound on HLE despite my fixes)

**Comment by notaz** [comment] 2023-10-16 21:59
Sound seems to work now.

**Closed by notaz** 2023-10-16 21:59 UTC
