### ISSUE TITLE
Tekken2 + (updated) lr-pcsx-rearmed = vertex explosions

### ISSUE THREAD

**Issue by patxipierce** [libretro/pcsx_rearmed#613] opened 2022-02-15 08:32 UTC
Hello all!

Thanks for your great emulator!

## Description

Last Friday I ran a full update. This updated several emulators, among them lr-pcsx-rearmed.

The problem is that now my Tekken 2 ROM has distorted graphics similar to the ones on [this post on reddit](https://www.reddit.com/r/RetroPie/comments/rti6r8/want_to_play_tekken_2_with_default_settings_on/).

The OP there solved the problem by reinstalling everything. Which must have downgraded his lr-pcsx-rearmed.

## Steps to reproduce

Update to the latest version of lr-pcsx-rearmed and load Tekken2, then go into any fight.

## When did the behavior start?

When I updated lr-pcsx-rearmed to its current version

## Your device/OS/platform/architecture

 Retropie - Linux 5.10.63-v7l+ armv7l GNU/Linux.

## Logs (enable file logging and set log levels to DEBUG for core and frontend)

None sorry.

## Screenshots (if needed for visual confirmation)

Please see here:
https://www.reddit.com/r/RetroPie/comments/rti6r8/want_to_play_tekken_2_with_default_settings_on/

**Comment by CometHunter92** [comment] 2022-02-15 16:22
I had these issues from the dynarec changes from december but the commits from january solved them.
Do you know how to manually put a core in RetroPie? I can send you the latest core compiled for the Pi4.

**Comment by quicksilver7837** [comment] 2022-02-15 18:07
If the issue is solved with latest version he would just need to select the "update from source" option in RetroPie setup to get the bleeding edge version.

**Comment by CometHunter92** [comment] 2022-02-15 19:07
Oh you're right, happens with the latest commits too.
Only a core from august work well.
Probably is the new dynarec from december and so on.

**Comment by patxipierce** [comment] 2022-02-15 21:09
Hello @CometHunter92 !

I'm not experienced enough to install cores without a little guidance, but if you point me to some docs I'll find out. On the retropie forum a kind soul told me ([link](https://retropie.org.uk/forum/topic/32221/tekken2-lr-pcsx-rearmed-vertex-explosions)) to use:

`git https://github.com/libretro/pcsx_rearmed.git master e007af2`

And to compile from source which fixed the issues. I can revert the changes and try and get the debug log with the bug if you think it would make the issue easier to fix.

Thanks for the help.

**Comment by notaz** [comment] 2022-02-15 23:46
This should be fixed now.

@gameblabla your icache stuff caused this on the interpreter side and I failed to notice during review, see 7baee56f47d66a45c3a04ec0c97164a837a34cf0 .

**Comment by gameblabla** [comment] 2022-03-03 19:03
Good to know, thanks for looking at it.

**Comment by notaz** [comment] 2022-04-08 21:34
This issue is expected to be fixed in the latest version. Feel free to reopen if it's not.

**Closed by notaz** 2022-04-08 21:34 UTC
