### ISSUE TITLE
CUE files fail if the file extension 'bin' is not UPPERCASE 'BIN'

### ISSUE THREAD

**Issue by krisnye** [libretro/pcsx_rearmed#143] opened 2017-12-02 23:41 UTC
Testing on RetroPie.

This cue file fails to load with error CD IMAGE not supported:

    FILE "Strider 2 (USA).bin" BINARY
        TRACK 01 MODE2/2352
            INDEX 01 00:00:00

Changing the file name to uppercase and it works

    FILE "Strider 2 (USA).BIN" BINARY
        TRACK 01 MODE2/2352
            INDEX 01 00:00:00

**Comment by SapphireTactician** [comment] 2018-04-19 02:38
Filenames and extensions are case sensitive. Is it uppercase in the actual filename as well? If so, that explains it. I can't reproduce this bug on my end. All of mine use lowercase extensions on both my x86_64 Debian PC and ARM Lakka boxes.

**Comment by hizzlekizzle** [comment] 2018-04-19 17:16
A lot of old cue sheets were written for Windows which uses case-insensitive filesystems. When you bring them into Linux/Retropie, which uses case-sensitive filesystems, these old cue sheets break. It could be worked around in the cue-parsing code, but I think that's a bad idea, since it could introduce weird edge-case behavior in certain situations.

**Comment by retro-wertz** [comment] 2019-03-12 00:22
rename the file to match within the .cue of rename the on in the cue.

**Comment by notaz** [comment] 2023-10-18 21:18
I'm closing this as this is an OS and not an emu core issue.

BTW nowadays it's possible to have case insensitive fs on Linux:
https://www.collabora.com/news-and-blog/blog/2020/08/27/using-the-linux-kernel-case-insensitive-feature-in-ext4/

**Closed by notaz** 2023-10-18 21:18 UTC
