### ISSUE TITLE
[Game] WWF In Your House Graphic problems

### ISSUE THREAD

**Issue by telanus** [libretro/pcsx_rearmed#420] opened 2020-05-18 22:06 UTC
##Description

In WWF In Your House (USA) (v1) The background is pixelated 

![WWF In Your House (USA) (v1 1)-200518-111200](https://user-images.githubusercontent.com/19357986/82263777-e9b53380-9963-11ea-9b31-031557fe2043.png)

##Your device/OS/platform/architecture

OS: Kubuntu 18.04 (64bit)
RetroArch: 1.8.7 (git https://github.com/libretro/RetroArch/commit/582f967fb03928da546ecfce0a1437aded19242c)

**Comment by negativeExponent** [comment] 2020-05-21 00:06
confirmed. with or without bios has the same issue. lightrec or interpreter same issue. switching between peops or unai gpu plugin same. Have not tested upstream.

**Comment by gameblabla** [comment] 2021-10-05 21:00
PCSX-Redux doesn't suffer from this bug. Given that the game throws up an invalid opcode error on lightrec and PCSX-Redux barely touched the GPU code at all, this game could need delayed loads support.

**Comment by pcercuei** [comment] 2023-09-22 11:46
I think this has been fixed in the interpreter since then. @notaz, do you remember what the fix was, or have an idea what could have fixed it?

**Comment by notaz** [comment] 2023-09-23 22:30
I haven't debugger this game before, but now that you brought it up and ari64 dynarec was still affected by this, it turned out to be this:
```
  8005b754: LWL r21,r21+d
  8005b758: LWR r21,r21+a
  8005b75c: NOP
```
Pretty nasty, isn't it?

**Comment by pcercuei** [comment] 2023-09-23 22:56
Ugh, what a terrible day to know MIPS assembly.

**Comment by notaz** [comment] 2023-10-24 19:56
This should work in all configurations now.

**Closed by notaz** 2023-10-24 19:56 UTC
Labels: bug, Lightrec
