### ISSUE TITLE
Core does not recognize games that contain non-standard characters anywere in the name or file path.

### ISSUE THREAD

**Issue by RhombusVoid** [libretro/pcsx_rearmed#231] opened 2019-02-26 01:36 UTC
Core does not recognize games that contain non-standard characters anywere in the name or file path. This is specific to the PCSX ReARMed core not Retroarch as a whole. Occuring on Windows 10 Retroarch 1.7.6. The characters specifically causing issues are Roman numerals haven’t tried others yet. Having one such character in the pathname causes the emulation to intantly stop as if it cannot find the file. Definitely not an issue with the files because removing the Roman numerals from the path allows the games to load normally

**Comment by Loquo** [comment] 2019-04-14 20:47
I suffer the same thing with "Spyro 3 - El año del dragón.bin/cue". The character "ñ" is a spanish letter. Also with "Ape Escape - La invasión de los monos.bin/cue" because the character "ó".

**Comment by AnotherLife** [comment] 2019-04-14 23:30
Until it is fixed rename the bin file and the cue file to Spyro 3.bin and Spyro 3.cue. Then edit the cue file with Notepad and change the filename there to the new one.

**Comment by Loquo** [comment] 2019-04-19 17:57
For me isn't really an important issue. Thanks anyway!

**Comment by negativeExponent** [comment] 2021-04-24 23:41
Duplicate of #https://github.com/libretro/libretro-fceumm/issues/448

**Comment by notaz** [comment] 2023-10-19 18:02
This was fixed in #516 from what I understand.

**Closed by notaz** 2023-10-19 18:02 UTC
