### ISSUE TITLE
[BUG?] Tekken 3 black screen after player's cinematic end

### ISSUE THREAD

**Issue by ben-so** [libretro/pcsx_rearmed#156] opened 2018-03-24 12:40 UTC
After a play through with any character a player specific cinematic is show. Afterwards usually the main menu is shown. But here's the problem: the screen goes black.

I searched for it and found something by PCSX-Reloaded at codeplex:
When you finish the arcade mode, after the player's end cinematic, the game doesn't restart. Instead, there is only a black screen.
 
PCSXR rev. 75200 with interpreter mode on
Plugins: GSdx 5100 1.16, P.E.Op.S Sound Audio Driver 1.10, Pokopom Xinput Pad Plugin 1.7, SaPu's CD-ROM Plugin 1.3.
Bios: SCPH-102
Closed
#9952 | Created 2012-02-22 | Updated 2013-05-16

Does anybody know, what was done back than or can find out, how it was fixed?
Please let me know, if I can provide any further information.

Version used is the one installed with Retropie 4.3.16

**Comment by ben-so** [comment] 2018-04-13 16:06
Is there any further information I can give to get support to solve this issue?

**Comment by gameblabla** [comment] 2021-10-06 21:18
It seems that this is possibly fixed now ?

**Comment by ben-so** [comment] 2021-11-02 19:19
I updated my retropie yesterday and tested again. Problem is the same, nothing has changed in this matter.

**Comment by notaz** [comment] 2023-10-18 22:31
Please provide a save file or some other way how to reproduce this.

**Comment by ben-so** [comment] 2023-10-20 13:20
Tekken doesn't use save files for that. You need to choose a charakter and complete the 10 fights. After that, a cinematic for the chosen charakter is played. Then my problem begins, as the screen turns black and you can wait to get to the main menu forever.

Let me add, that I haven't tried it for some time.

**Comment by notaz** [comment] 2023-10-20 22:25
I guess I wasn't specific enough. Emulators have a traditional feature called "save states" where you can save at any moment regardless what the game supports, which is what I'm was for. Libretro/RetroArch generates .state files which can be attached to bug reports like this.

**Comment by notaz** [comment] 2023-10-29 23:23
I'm closing this since many similar bugs have been fixed and I have no way to reproduce. You can always open another one if needed.

**Closed by notaz** 2023-10-29 23:23 UTC
Labels: Testers wanted
