### ISSUE TITLE
[3DS CIA] No CHD support?

### ISSUE THREAD

**Issue by francescoseu** [libretro/pcsx_rearmed#355] opened 2019-10-07 10:19 UTC
PCSX ReARMed core for Nintendo 3DS (CIA) is unable to load games in CHD format, I get "Failed to load content" error message in 2nd screen log. Some CHD files get me back on RetroArch's main menu on failure, some boot me back to the 3DS system menu.

**Comment by Bonethugs1980** [comment] 2019-10-07 13:40
CHD does work.  However, it doesn't work well as mentioned.  There's still plenty of work (optimisations to be done, it appears).  Some of the emulator settings don't seem to take actual effect e.g. 'Parasite Eve 2 fix' (eboot, bin or chd) game does not start after opening 'Mist Description').  Dino Crisis doesn't go into main menu, it boots then crashes with eboot (chd/bin ran, but was slow, sluggish with audio problems).

You are better off using 'eboot.pbp' format; it has better compatibility generally chd works similar to bin with speed/fps issues, at least with the games I tested running either at 59 or 60fps ish:

Alone in the Dark
Alundra
Countdown Vampires
Covert Ops - Nuclear Dawn
Deep Freeze
Dino Crisis 2
Fear Effect
Fear Effect 2 - Retro Helix
Galerians
Parasite Eve
Policenauts
Resident Evil 2/3
Silent Hill
Soul of the Samurai
T.R.A.G.

**Comment by francesco-seu** [comment] 2019-10-07 14:28
Got it, I'll try with a game converted with PSX2PSP later today and I'll let you know if it works

**Comment by justinweiss** [comment] 2019-10-09 00:39
CHDs should work. Which games did you try? It sounds like there are some games that don't work in CHD, but I haven't run into any of them yet. 

PBP should work just as well, the performance boost comes from having a smaller file, and PBP and CHD are about equal there.

**Comment by ryder-5152** [comment] 2019-10-09 09:29
> CHDs should work. Which games did you try? It sounds like there are some games that don't work in CHD, but I haven't run into any of them yet.
> 
> PBP should work just as well, the performance boost comes from having a smaller file, and PBP and CHD are about equal there.

I tried with Crash Bandicoot and Oddworld: Abe's Oddysee (my go-to choices when I want to try a PSX emulator/core) and I think another one or two random games.
Now, I can't remember which game(s) booted me back to the 3DS menu and which got me back to the RetroArch main menu, but they all didn't start with "Failed to load content" or something like that.

It's worth mentioning that the exact same CHDs run fine on RetroArch on my PC and on my Raspberry Pi 3B+ with RetroPie (using lr-pcsx-rearmed), so maybe we can rule out any issue with the files themselves.

I then tried Crash Bandicoot converted in PBP format and it ran, albeit with slowdowns here and there (eg. on the map and while inside levels, fullspeed in the main menu and on the completion screens between levels, but maybe I should hope and wait for further core optimizations :grin: ).

**Comment by negativeExponent** [comment] 2019-12-18 06:01
> > CHDs should work. Which games did you try? It sounds like there are some games that don't work in CHD, but I haven't run into any of them yet.
> > PBP should work just as well, the performance boost comes from having a smaller file, and PBP and CHD are about equal there.
> 
> I tried with Crash Bandicoot and Oddworld: Abe's Oddysee (my go-to choices when I want to try a PSX emulator/core) and I think another one or two random games.
> Now, I can't remember which game(s) booted me back to the 3DS menu and which got me back to the RetroArch main menu, but they all didn't start with "Failed to load content" or something like that.
> 
> It's worth mentioning that the exact same CHDs run fine on RetroArch on my PC and on my Raspberry Pi 3B+ with RetroPie (using lr-pcsx-rearmed), so maybe we can rule out any issue with the files themselves.
> 
> I then tried Crash Bandicoot converted in PBP format and it ran, albeit with slowdowns here and there (eg. on the map and while inside levels, fullspeed in the main menu and on the completion screens between levels, but maybe I should hope and wait for further core optimizations grin ).

confirm that you do have the latest version of the core.

**Comment by ryder-5152** [comment] 2019-12-18 11:18
When I opened this issue I was using the latest RetroArch stable at the time, which (if I recall correctly) should be v1.7.8.

I currently don't have access to my 3DS and I can't remember if I updated RA in the meantime (but I can tell you I stopped trying CHD games after opening this issue), but judging from the .info file included with 1.7.8, the version of the core should be **r21**, also there is **chd** among the list of supported extensions in the `.info` file.

I could try updating to v1.8.1 and try a CHD or two again when I get my 3DS and see how it goes, even though there is `display_version = "r21"` in `pcsx_libretro.info` in RetroArch 3DS v1.8.1 as well.

**Comment by Bonethugs1980** [comment] 2019-12-18 18:17
The issues we've seen or had won't be quick fixes until they stabilise the emulator and decide on a specific container format e.g. CHD, PBP etc.  Having many different formats to choose form is somewhat annoying.

Some games work, some don't as others noted above.  I am from the UK with a UK 3DS but tend to use the US roms, usually they run at 59/60fps were applicable and depending if that game is fully supported by the emulator.

Parasite Eve 2 doesn't work, it will go to the squaresoft logo screen, then show black.  The game appears to still be working/running you just can't select or do anything (regardless of emulator settings to fix boot issue - can't remember the setting].  This points to the emulator itself being the problem.  Even when trying to not use the GPU core, it will boot and load past the black screen, this time showing text, then crash.

Most of the other 3d high res background games run perfectly fine - Alone in the Dark The New Nightmare, Parasite Eve 1, RE2, RE3, Dino Crisis 2, Deep Freeze, (Japanese only release game with English audio, but Japanese text for dialogue).

Since priorities are towards the PC, consoles and switch.  The 3ds in my opinion will be behind the rest.

**Comment by negativeExponent** [comment] 2019-12-20 06:03
> The issues we've seen or had won't be quick fixes until they stabilise the emulator and decide on a specific container format e.g. CHD, PBP etc. Having many different formats to choose form is somewhat annoying.
> 
> Some games work, some don't as others noted above. I am from the UK with a UK 3DS but tend to use the US roms, usually they run at 59/60fps were applicable and depending if that game is fully supported by the emulator.
> 
> Parasite Eve 2 doesn't work, it will go to the squaresoft logo screen, then show black. The game appears to still be working/running you just can't select or do anything (regardless of emulator settings to fix boot issue - can't remember the setting]. This points to the emulator itself being the problem. Even when trying to not use the GPU core, it will boot and load past the black screen, this time showing text, then crash.
> 
> Most of the other 3d high res background games run perfectly fine - Alone in the Dark The New Nightmare, Parasite Eve 1, RE2, RE3, Dino Crisis 2, Deep Freeze, (Japanese only release game with English audio, but Japanese text for dialogue).
> 
> Since priorities are towards the PC, consoles and switch. The 3ds in my opinion will be behind the rest.
> 
> Note - this is since PCSX core was updated back mid this year up to 1.8.1 just re-tested. Basically, not much difference, yet...

most of the issue you stated is not exclusive to 3DS but every dynarec (most at least) have these issues compared to non-dynarec builds. It does not help that reports have incomplete descriptions or people just post reports and never come back, not to mention that the core is maintained by volunteers.

**Comment by Bonethugs1980** [comment] 2019-12-20 10:47
True enough, yes.  Just like with PC (or any other widely used system) when people have issues with the operating system behaviour or games booting up, working, not working etc (generally speaking) - somebody's issue, is not somebody else's nor does it replicate the same way.

I would say the initial announcement of 'pcsx rearmed games running at 60fps' should have been taken with a grain of salt by the community or people that replied to the thread on reddit expecting it to work flawlessly from that build.  The emulator does work with games mentioned and a fair few that aren't mentioned. 

Of course we wouldn't have these in the first place if it wasn't for the work going into them.  The announcement was a surprise.  I had used it once or twice, back when the earliest version of the core was made available and left it for awhile prior to the Sept 2019 post (on reddit).

wasn't sure from your comment if you were frustrated with what we've added here - 'It does not help that reports have incomplete descriptions or people just post reports and never come back' or just generally?

**Comment by justinweiss** [comment] 2019-12-24 00:29
For what it's worth, I've converted all of my PSX games to CHD, and they're running well on N3DS -- there could be specific games that are incompatible, though, and it would be good to know about them. It's worth another test on the newest builds if you haven't tried it in a while. PBP should work just as well, but I find chdman easier.

There was a rough patch right around the time the 3DS improvements were made in late September / early October. Specifically, I made a change to fix CD Audio that ended up causing some games to crash. It was fixed right away, but the broken version was a stable release and the fixed one was not, so it stuck around for a while.

The random dynarec crashes are still really annoying and inconsistent. Unfortunately, the crash logs haven't been much help, because the stack trace and registers don't point to anything. I have some wild guesses (maybe the dynarec is generating instructions that the 3DS doesn't support? Maybe there's a memory permission difference between 3DS and whatever the dynarec was written for? Maybe there's a performance factor? etc.) but I don't know enough about how the PCSX / gpSP dynarecs work to dive into them.

For other crashing bugs, especially reproducible ones, crash reports are still helpful. Especially if you have a specific game / situation / savestate that show it.

**Comment by Bonethugs1980** [comment] 2020-01-15 18:38
Is the Unai GPU the best option for the 3ds?  Also, this explains the container format better, no wonder the eboots aren't 100% since it's partially supported (correct me if wrong):

https://github.com/notaz/pcsx_rearmed/blob/master/readme.txt
'Supported CD image formats:
- .bin/.cue
- .bin/.toc
- .img/.ccd/.sub
- .mdf/.mds
- .Z/.Z.table
- .bz/.bz.table
- .ZNX/.ZNX.table (partial)
- EBOOT.PBP (PSP, partial)
- .cbn'

**Comment by francescoseu** [comment] 2020-02-03 13:52
A little update: today I've updated RetroArch 3DS to the latest stable (which, at this time, is v1.8.4) and I don't know what has changed, but now not only do CHD games load for me, but they also run almost at fullspeed with sound on and no frameskip. There are the occasional hiccups here and there, but all in all, they're surely more playable than they were in PBP format :)

I don't know if it can be related, but in the meantime I did change my Micro SD card to a bigger one (256GB) and I enabled game patching in Luma to solve (it's more of a workaround imho) a bug in Anemone 3DS, as described [here](https://github.com/astronautlevel2/Anemone3DS/issues/210#issuecomment-524060082).

**Comment by Bonethugs1980** [comment] 2020-02-03 15:11
Have you tried Parasite Eve 2 by any chance as CHD? That's never worked on the 3ds version of PCSX rearmed as eboot.

**Comment by francescoseu** [comment] 2020-02-03 15:12
> 
> 
> Have you tried Parasite Eve 2 by any chance as CHD? That's never worked on the 3ds version of PCSX rearmed as eboot.

Not yet, but I have it so I might try it while getting back home from work. I'll get back to you as soon as I try.

**Comment by francescoseu** [comment] 2020-02-04 08:53
@Bonethugs1980
> 
> 
> Have you tried Parasite Eve 2 by any chance as CHD? That's never worked on the 3ds version of PCSX rearmed as eboot.

Unfortunately it doesn't work. Even with the "Parasite Eve 2 fix" core option enabled, I can only watch the opening cutscene and then it gets stuck on a black screen. At least it doesn't completely crash the 3DS so I can always open the menu and close the content.

**Comment by Bonethugs1980** [comment] 2020-02-04 14:11
Cheers for taking a look.

**Comment by negativeExponent** [comment] 2020-02-04 21:41
parasite eve 2 has nothing to do anymore with that Prasite Eve 2 fix core option( that has to be removed since its has been confirmed to be not working anymore). Dynarec fixes usually are fixed with the overclock option, usually set to 75

**Comment by negativeExponent** [comment] 2020-11-04 12:31
so i guess the issue is resolved?

**Closed** 2021-10-08 17:50 UTC
