### ISSUE TITLE
[New 3DS 1.9.11 Stable] RetroAchievements not compatible with CHDs

### ISSUE THREAD

**Issue by UltraSyko** [libretro/pcsx_rearmed#554] opened 2021-08-26 16:59 UTC
## Description
Achievements don't work

## Steps to reproduce
Try a CHD of Pepsiman on New 3DS and then on DuckStation. 

## When did the behavior start?
It never worked before.

**Comment by Syko7956** [comment] 2021-09-09 01:25
Still happens in 1.9.9 Stable

**Comment by MrHuu** [comment] 2022-01-07 13:47
While the core has .CHD support, retroarch (the frontend) is build without it.
Every core (for 3DS) with .CHD support has this same issue currently.

This is not a core issue, but instead it's an issue related to retroarch.
As indicated here: https://github.com/libretro/RetroArch/issues/10841

Building retroarch with ```HAVE_CHD``` enabled, allows the fronted to stream .chd's required for achievements to be functional.

While it seems to be working on my end, i'm unable to test multiple cores with various chd's to actually verify it won't cause issues. This and the fact that PCSX-ReARMed is currently in a non-functional state, prevent me from making the required pr.

Here's a build based on 589bd99ba31de8216624dbf0cbbc016f0663ce3d, with chd support enabled.
If you could verify the achievements are functional, it would be very much appreciated.

[pcsx_rearmed_libretro.zip](https://github.com/libretro/pcsx_rearmed/files/7829127/pcsx_rearmed_libretro.zip)

**Comment by Syko7956** [comment] 2022-01-13 13:43
Just tried it and...IT WORKS! Confirmed with Klonoa 
![image](https://user-images.githubusercontent.com/16283463/149341114-0ec680b1-b46e-4ce1-a795-9f55c25af84a.png)

**Comment by MrHuu** [comment] 2022-01-23 15:11
My apology, while PCSX-ReARMed is able to be build with frontend CHD support, some other cores are not. https://github.com/libretro/RetroArch/pull/13512

Due to how the current required ```libchdr``` is included with ```libretro-common```, it's not possible to build the entire Retroarch project with CHD support enabled. For the time being, frontend CHD support will stay disabled.

Building just PCSX-ReARMed, with CHD support, would still be an option when building the project from source.

**Comment by UltraSyko** [comment] 2022-01-23 20:03
Yeah, I saw the sad news. Well, I'm glad you still found a workaround and I don't think I'm missing out on updates. So, I think I'm satisfied with this build. I guess I'll keep the issue open(?)

**Comment by notaz** [comment] 2023-10-24 20:35
Closing as this doesn't look like a core issue.

**Closed by notaz** 2023-10-24 20:35 UTC
