### ISSUE TITLE
Poporogue wont load after 1st scene

### ISSUE THREAD

**Issue by Navarongunner** [libretro/pcsx_rearmed#303] opened 2019-06-21 11:43 UTC
Game: Poporogue - NTSC Japan
core: Pcsx Rearmed standard version from KMFDManic release
System: Snes Classic 

Poporogue start and after the first sequence the character move to another room and then speach keep going but no screen is loaded, the game stay black screen until speach is over and then its just keep playing the bgm 
Also the speach is out of sync since start

**Comment by bslenul** [comment] 2019-06-21 12:50
I can reproduce on PC with W10, black screen as soon as the character left the room, you can still hear the voice but the screen stays black.

**Comment by gameblabla** [comment] 2021-10-02 01:01
Probably fixed since https://github.com/libretro/pcsx_rearmed/commit/d2e271b26ef7e8c61a371fe5fa71003e7691118e but i'm still putting the tags just in case

**Comment by notaz** [comment] 2023-10-19 19:41
Closing as per previous comment, reopen if there is still an issue.

**Closed by notaz** 2023-10-19 19:41 UTC
Labels: bug, Testers wanted
