### ISSUE TITLE
[Lightrec] Sled Storm freezing after the FMV intro

### ISSUE THREAD

**Issue by bslenul** [libretro/pcsx_rearmed#664] opened 2022-06-05 14:28 UTC
Sled Storm (only tested with the US version) has some issues:

* ~~Musics are playing waaaaay too fast, already bisected, started to happen with 66425c25db8a6e4d33488977bf745af73dbe8b39, it happens on Windows and Android, with or without HLE BIOS, with or without dynarec.~~

**edit:** ^ This is an upstream issue, issue opened there: https://github.com/notaz/pcsx_rearmed/issues/250

* On Windows with dynarec enabled the game freezes after the intro FMV (or if you skip it). The issue doesn't happen with HLE BIOS, and it also doesn't happen on Android. Haven't bisected that one yet.

**Comment by bslenul** [comment] 2022-06-06 23:12
I wasn't able to bisect properly due to build errors, but it started to happen somewhere between 641d7badb70e58c4fbab04fa70212e6e7b7cdaaa (game doesn't freeze) and d51bb08a1aedb5b20f0a73d101942825ceac5ef3 (game freezes just like it does currently).

@pcercuei

**Comment by pcercuei** [comment] 2022-06-07 17:33
Fixed in https://github.com/pcercuei/lightrec/commit/8ef8e096f2012b96b18daebe1905a2b528a2565c

Keep them coming.

**Comment by bslenul** [comment] 2022-06-07 19:08
Nice, thanks for the fix!

Works fine, but I noticed that the musics don't play. It doesn't seem to be something new tho, I tried a commit from March 2021 and there was no music already. They play fine with the HLE BIOS.

**Comment by bslenul** [comment] 2022-06-07 19:15
Nope, musics work fine if I disable dynarec, with and without a real BIOS.

**Comment by pcercuei** [comment] 2022-06-07 19:25
- Try to run with Lightrec's interpreter (set the LIGHTREC_INTERPRETER=1 environment variable). If it works, then the problem is a codegen error;
- Try to disable optimizations: set the OPT_* macros to 0 in include/lightrec/lightrec-config.h. If it works with both Lightrec's dynarec and Lightrec's interpreter, then the problem is in one of the optimization passes.

**Comment by pcercuei** [comment] 2022-06-07 22:16
It does work with Lightrec's interpreter here.

**Comment by bslenul** [comment] 2022-06-07 22:29
I was about to post that it worked by forcing interpreter to "true" here: https://github.com/libretro/pcsx_rearmed/blob/6658ddcf5dec8d6e22363fb435c48dfe4ce1e7f8/libpcsxcore/lightrec/plugin.c#L329

Not sure why it didn't work with `LIGHTREC_INTERPRETER=1 make -f Makefile.libretro` (also tried with `export LIGHTREC_INTERPRETER=1` before make) 🤷 

So yeah, sorry about that :/

**Comment by pcercuei** [comment] 2022-06-07 23:10
Because you need to set it at runtime, not at compile time: `LIGHTREC_INTERPRETER=1 retroarch`

**Comment by bslenul** [comment] 2022-06-07 23:24
Oooooh I see! Well I feel dumb, but at least I'll know for next time :p Thank you for the info!

**Closed** 2022-06-11 09:46 UTC

**Comment by pcercuei** [comment] 2022-06-11 09:49
Since the feezing issue is fixed, this bug report was closed; @bslenul please re-open the no-music issue in the lightrec repo's bug tracker.
