### ISSUE TITLE
Lightgun: Point Blank 1 graphical bug (missing calibration crosshair)

### ISSUE THREAD

**Issue by StormedBubbles** [libretro/pcsx_rearmed#573] opened 2021-10-21 22:20 UTC
## Description

Issues on Pi 3 and Pi 4:

Point Blank 1: When GunCon activated, crosshairs do not appear during gun calibration. Calibration DOES work, so it seems to just be a graphical glitch.

Gunfighter: The Legend of Jesse James: GunCon does not function at all. Emulator thinks no controller is plugged in.

## Steps to reproduce

Changes from default settings: P1 & P2 devices set to GunCon (Point Blank), P1 device set to GunCon (Jesse James).

For Point Blank: the game starts with a calibration menu when gun devices are connected. You are supposed to shoot the center to calibrate your gun. After shooting, you are supposed to see an icon that moves with your gun (Point Blank 2 and 3 work properly). This icon does not appear for Point Blank 1. The calibration process DOES seem to work, so this is more of a graphical glitch.

For Gunfighter: The Legend of Jesse James: start the game with P1 device = GunCon. No buttons will register, and once the introductory cinematic finishes, the game will prompt you to plug in a controller.

All other GunCon games appear to work correctly.

## When did the behavior start?

Both seem to have been issues since lightgun support added.

## Your device/OS/platform/architecture

Pi 3 and Pi 4.

(EDIT: formatting)

**Comment by capitaineflam25** [comment] 2021-12-17 06:26
I reproduce those bugs.

I' m also unable to start "Resident Evil Survivor", the situation seems similar as it is in Gunfighter.

**Comment by StormedBubbles** [comment] 2021-12-17 12:32
Which version of Resident Evil Survivor are you using? The North American version doesn't have GunCon support out of the box. I added it with an external patch that I found floating out there on the Internet. With the Japanese, European/PAL, or the patched North American version, the GunCon support works fine in this emulator. The controls are quite complicated and are described in the manual.

**Comment by capitaineflam25** [comment] 2021-12-17 13:28
I'm using the USA version.

When tryng to play the European/PAL version here is what i'm facing (the guncon is enabled on retroarch controller menu)

![IMG_20211217_142303](https://user-images.githubusercontent.com/985702/146551489-f1803ca1-0234-4793-bdac-3692b6e38964.jpg)

**Comment by StormedBubbles** [comment] 2021-12-17 13:48
Did you try patching the USA version? For that version, it's port 1 = guncon and port 2 = standard controller. The game takes me to a calibration screen where I can calibrate my gun. The USA version does not support any gun controller otherwise.

What I see there is a message that displays when the GunCon is not detected on startup. Do you have the GunCon activated before booting?

**Comment by capitaineflam25** [comment] 2021-12-17 14:07
(Sorry i was testing the wrong game on my deleted post)

Thanks a lot for your help :
I confirm both the Japanese and USA+Patch version are detecting the Guncon (Using an USB Mayflash Dolphin bar, simulating a mouse)

But i'm unable to exit the calibration screen (i've set input_player1_gun_aux_b_mbtn and input_player1_gun_aux_a_mbtn to the same button to simulate the simultaneous press)


![IMG_20211217_150229](https://user-images.githubusercontent.com/985702/146556329-978b8e49-8d46-4257-b11e-df0c044f0e47.jpg)

**Comment by StormedBubbles** [comment] 2021-12-17 14:09
This emulator has the GunCon buttons hard coded on my end. I press mouse buttons 2 and 3, which are right click and scroll-wheel click, to exit that screen.

**Comment by capitaineflam25** [comment] 2021-12-17 14:34
Oh nice !

Since the Mayflash Dolphin Bar has no third button, it worked by doing the following :
- do the calibration with the Wiimote
- unplug the Mayflash DolphinBar and plug a mouse
- press button 2+3 to exit calibration
- plug back the Mayflash DolphinBar

and you're done 🤩

**Comment by Tovarichtch** [comment] 2023-09-08 00:52
Almost two years later, the issue with _Gunfighter: The Legend of Jesse James_ persists.

**Comment by StormedBubbles** [comment] 2023-09-15 00:00
The issue with Gunfighter: The Legend of Jesse James was resolved with 1e774d8

**Comment by Tovarichtch** [comment] 2023-09-15 00:26
Fantastic!

**Comment by capitaineflam25** [comment] 2023-09-15 04:04
Yeah ! Thanks !

**Comment by notaz** [comment] 2023-12-02 22:26
I think all issues mentioned here are now solved, closing.

**Closed by notaz** 2023-12-02 22:26 UTC
