### ISSUE TITLE
Wild Arms has multiple issues (raspberry pi3)

### ISSUE THREAD

**Issue by wolfspirit00** [libretro/pcsx_rearmed#315] opened 2019-07-25 12:48 UTC
Wild Arms has multiple issues when playing on reARMED (both the libretro branch and regular one). Playing on a Raspberry Pi3, Retropi. Made sure everything is up to date as far as I can tell. I know I'm not the only one who's had this issue because when I googled it someone else had the same issue years ago, but they switched to playing elsewhere so never found a fix or saw all of the problems.

1) Can't make magic. When you try to make a spell on a crest graph, it never tells you the description of what the spell should do (which it should), and when you blindly decide to choose something anyway, it then freezes up in a soft lock. Music plays but no input works. (Game breaking, but can be worked around with cheats)
2) Rudy has a glitched texture when in battle. (Annoying but seems to only be a visual glitch)
3) Talking to a man inside the in on the day of the festival soft locks the game. Again like before, music plays, nothing is in his text box, no inputs work. (Pretty sure you don't need to talk to him.)
4) Trying to buy equipment for someone in your party also freezes the game. Example. You have Jack and Rudy in your party, you try to buy a weapon or armor that either one can use, soft lock. The screen still plays music and the arrow showing if it's an upgrade or downgrade from what you have still is flashing, but can't do anything. (Game breaking, but can be worked around with cheats)
5) After you speak with the king after the attack during the festival, it fades out and it doesn't come back. Totally locked up. This one is unfortunately impossible to use a little cheat to deal with. (Permanently game breaking. Absolutely NO way to get past this one)

If there is ANY way to fix this or a work around, please let me know. This is easily my favorite game on the system.

I made sure it isn't the game file itself. I also, like I said, tested on both versions of reARMED. (The non lib version did say it was running as PAL when it shouldn't be since it should be a NTSC game, so I don't know if that is a contributing factor or not, and I'm not sure how to fix that anyway)

**Comment by retro-wertz** [comment] 2019-07-29 02:04
provide a save state and save file for easier confirmation would be helpful, else someone has to play upto certain points in the game.

in any case, which one of these 5 points is the fastest to reach and confirm.

**Comment by negativeExponent** [comment] 2020-02-13 01:24
this should be safe to close, since the problem was using HLE bios. or at least tag with HLE

**Comment by negativeExponent** [comment] 2020-11-04 12:36
use official bios (i dont even understand why not to). fixed. done. case closed

**Comment by gameblabla** [comment] 2021-10-02 00:59
I believe this should be fixed ever since my HLE patches, but it's possible it's still there. These look like core issues with some of the BIOS functions.

**Comment by notaz** [comment] 2023-10-19 20:03
If this is still an issue, please provide savestates shortly before the issues occur. Otherwise it's just too much work to check issues like this. Closing for now.

**Closed by notaz** 2023-10-19 20:03 UTC
Labels: HLE

**Comment by negativeExponent** [comment] 2023-10-20 00:15
hi @notaz thanks for the constant updates of this core :D

i have tested this issue before. it was caused by using HLE bios and most Konami games (unable to save to memory card, missing gfx and such etc). Im not sure if this is still a problem with recent updates. I'll try to create savestates or at least a procedure on how to replicate the issue stated when im able to (unless someone beats me to it)
