### ISSUE TITLE
Psybadek Starts then Stops

### ISSUE THREAD

**Issue by pheedback** [libretro/pcsx_rearmed#418] opened 2020-05-15 15:12 UTC
I am running lr-pcsx-rearmed on a Raspberry Pi 4. I asked over on their forums about the issue, but they said that Psybadek may not be compatible with the emulator. I was wondering if someone could confirm if Psybadek is not compatible. When I try to run the NTSC-U or the PAL version the game starts up then shuts down. For the NTSC-U game I can hear some of the audio start up then it closes. For the PAL version it will show the piracy screen and then close out. The screenshot is the message I see when the NTSC-U game closes on my Raspberry Pi 4. If the game is compatible what steps should be done to get it to work. I originally was trying to use an overlay(bezel) and the zfast curved pi shader, but I have switched those off and still have the same issue. I have tried also changing the screen resolution for the game, but that has no effect. Would anyone happen to have a list of the games that are supposed to be compatible with the lr-pcsx-rearmed emulator?

![1589510598922-screenshot_20200514-223544](https://user-images.githubusercontent.com/30811242/82065644-5eeee300-969c-11ea-8c1b-b7a30156f6b0.png)

**Comment by negativeExponent** [comment] 2020-05-17 06:57
try playing with official bios, if you are not using one.
the piracy error on pal might mean you need .sbi file.

**Comment by gameblabla** [comment] 2021-10-02 01:09
I believe this could be a dynarec issue too if the game cannot be run on ARM. I do have another bug on that game (no CDDA music but it was working on stock PCSX Rearmed, probably because i didn't merge my Fantastic pinball fix yet) but that one should be fixed easily.

This needs more details from OP to make sure it works on his PC too.

**Comment by gameblabla** [comment] 2021-10-02 01:28
Uh, it actually crashes on ARM, interesting. Well i guess we might be dealing with a dynarec crash issue like WWF In your house... : /

**Comment by notaz** [comment] 2022-04-08 22:01
The ARM dynarec bugs are thought to be fixed. Feel free to reopen in case there are still issues, preferably with an explanation how to quickly reproduce.

**Closed by notaz** 2022-04-08 22:01 UTC
Labels: bug, Help wanted, ARM dynarec
