### ISSUE TITLE
[New 3DS 1.9.10 Stable] Multi Track games crash on .CHD 

### ISSUE THREAD

**Issue by Syko7956** [libretro/pcsx_rearmed#534] opened 2021-08-06 20:39 UTC
Games with multiple audio tracks will crash. It doesn't crash on the same core on PC or Duckstation. I tried with both clean default settings and custom settings AFTER deleting the old cfg. 

## Steps to reproduce
**Pepsiman**: Opening FMV works fine; Crashes at title screen (<-- I recommend this for the fastest test)
**Advanced V.G.**: Opening company logos work; crashes loading title screen
**In the Hunt**: logo credits, title, short radar cutscene works; crashes the moment you start the level.
**Gundam Battle Assault**: logo credits, title, memory card saving, menus character select, mech select, and cutscenes work; crashes the moment you start the fight

## When did the behavior start?
The last stable build that worked was 1.9.3. 1.9.4 broke it. Thank you, ClickPond for clarifying!
People on GBAtemp have expressed also crashing in similar ways. 

[logs.zip](https://github.com/libretro/pcsx_rearmed/files/6947887/logs.zip)

**Comment by Syko7956** [comment] 2021-09-09 01:25
Still happens in 1.9.9 Stable

**Comment by FallGuy308** [comment] 2021-09-15 16:19
dietz nuts

**Comment by Syko7956** [comment] 2021-09-28 09:58
Edited. Thank you!

**Comment by gameblabla** [comment] 2021-10-02 01:37
With Fantastic Pinball when i was experimenting with my patch, PCSX rearmed was crashing when CHD was used due to the threading code used for CDDA music tracks.
I'm not sure if that's the case of it or not but it would be good to know.
https://git.libretro.com/libretro/pcsx_rearmed/-/jobs/913778

If you could help me test my changes, it would be good to know so we can scratch that off and make sure it's really a regression.

**Comment by bulzipke** [comment] 2021-10-02 13:04
https://user-images.githubusercontent.com/15259720/135717399-76cac427-5188-42e2-8bb9-290cf490cd38.mp4

Finally!!
(Watch out the volume)

Run with Rayman(chd) by 66425c25 build(3dsx)
Thanks you, @gameblabla !!

**Comment by gameblabla** [comment] 2021-10-02 13:09
Well i guess i should just merge my PR and deal with the rest later.

**Comment by gameblabla** [comment] 2021-10-02 13:10
https://github.com/libretro/pcsx_rearmed/pull/552 is merged so let's close this issue. The nightly builds should have the fix asap.

**Closed by gameblabla** 2021-10-02 13:10 UTC

**Comment by bulzipke** [comment] 2021-10-02 13:22
https://github.com/libretro/pcsx_rearmed/issues/521
relate issue

**Comment by gameblabla** [comment] 2021-10-02 13:31
Thanks, i believe https://github.com/libretro/pcsx_rearmed/issues/550 also suffers from this as well.

**Comment by bulzipke** [comment] 2021-10-02 13:34
@gameblabla , I'm afraid but I found another bug.
Rayman can run well since #552, but cannot play CDDA music track.
Would it be better to open this up as a new issue?

**Comment by gameblabla** [comment] 2021-10-02 13:36
> @gameblabla , I'm afraid but I found another bug. Rayman can run well since #552, but cannot play CDDA music track. Would it be better to open this up as a new issue?

You most likely suffer from the same issue as https://github.com/libretro/pcsx_rearmed/issues/549.
I would just add a comment to that bug report if the CDDA music plays in bin/cue format.

**Comment by bulzipke** [comment] 2021-10-02 13:40
That's an issue that duplicate with this.
Thank you for your hard work!

**Comment by Syko7956** [comment] 2021-10-02 14:10
Perfect! Thank you all for fixing this long lasting issue. All we need now is achievements working on CHDs.
