### ISSUE TITLE
 "Error opening CD-ROM plugin!" Message when opening Ape Escape PAL/European version

### ISSUE THREAD

**Issue by Casalu** [libretro/pcsx_rearmed#555] opened 2021-08-29 09:48 UTC
## Description

"Error opening CD-ROM plugin!" Message when opening Ape Escape (PAL version)

## Steps to reproduce

Try to load Ape Escape (PAL Version) Game doesn't boot and the program is closed.

## When did the behavior start?

I think the build available on May 2021 worked fine but I'm not sure if it was updated at the time.
But this wasn't a problem for years, that's for sure.

## Your device/OS/platform/architecture

Rasberry Pi 4 B using Retropie

## Logs

Parameters: 
Executing: /opt/retropie/emulators/retroarch/bin/retroarch -L /opt/retropie/libretrocores/lr-pcsx-rearmed/pcsx_rearmed_libretro.so --config /opt/retropie/configs/psx/retroarch.cfg "/home/pi/RetroPie/roms/psx/Ape Escape.cue" --verbose --appendconfig /dev/shm/retroarch.cfg
[INFO] RetroArch 1.9.7 (Git 8373ac6)
[INFO] === Build =======================================
[INFO] Capabilities:  NEON VFPv3 VFPv4
[INFO] Built: Jul 29 2021
[INFO] Version: 1.9.7
[INFO] Git: 8373ac6
[INFO] =================================================
[INFO] [Input]: Found input driver: "x".
[INFO] [Core]: Loading dynamic libretro core from: "/opt/retropie/libretrocores/lr-pcsx-rearmed/pcsx_rearmed_libretro.so"
[INFO] [Overrides]: No core-specific overrides found at "/home/pi/.config/retroarch/config/PCSX-ReARMed/PCSX-ReARMed.cfg".
[INFO] [Overrides]: No content-dir-specific overrides found at "/home/pi/.config/retroarch/config/PCSX-ReARMed/psx.cfg".
[INFO] [Overrides]: No game-specific overrides found at "/home/pi/.config/retroarch/config/PCSX-ReARMed/Ape Escape.cfg".
[INFO] [Environ]: GET_LOG_INTERFACE.
[INFO] [Environ]: SET_CONTROLLER_INFO.
[INFO] [Environ]: GET_CORE_OPTIONS_VERSION.
[INFO] [Environ]: GET_LANGUAGE: "0".
[INFO] [Environ]: RETRO_ENVIRONMENT_SET_CORE_OPTIONS_INTL.
[INFO] [Remaps]: Remap directory: "/opt/retropie/configs/psx/".
[INFO] [Overrides]: Redirecting save file to "/home/pi/RetroPie/roms/psx/Ape Escape.srm".
[INFO] [Overrides]: Redirecting save state to "/home/pi/RetroPie/roms/psx/Ape Escape.state".
[INFO] [Environ]: GET_MESSAGE_INTERFACE_VERSION.
[libretro INFO] Memcard 2: disabled
[libretro INFO] Starting PCSX-ReARMed 
[libretro INFO] Running PCSX Version 1.9 (Aug 26 2021).
[libretro INFO] Init new dynarec
[libretro INFO] testing if we can run recompiled code..
[libretro INFO] test passed.
[libretro INFO] Mapped (RAM/scrp/ROM/LUTs/TC):
[libretro INFO] 80000000/1f800000/1fc00000/08000000/aeb76000
[INFO] [Environ]: SYSTEM_DIRECTORY: "/home/pi/RetroPie/BIOS".
[libretro INFO] found BIOS file: psxonpsp660.bin
[INFO] [Environ]: GET_CAN_DUPE: true
[INFO] [Environ]: GET_DISK_CONTROL_INTERFACE_VERSION.
[INFO] [Environ]: SET_DISK_CONTROL_EXT_INTERFACE.
[INFO] [Environ]: GET_RUMBLE_INTERFACE.
[INFO] [Environ]: PERFORMANCE_LEVEL: 6.
[INFO] [CONTENT LOAD]: Content loading skipped. Implementation will load it on its own.
[INFO] [Environ]: SET_INPUT_DESCRIPTORS:
[INFO] [Environ]: SET_PIXEL_FORMAT: RGB565.
[libretro INFO] RGB565 supported, using it
[libretro INFO] plugin: plugins/builtin_gpu
[libretro INFO] plugin: plugins/builtin_spu
[libretro INFO] plugin: plugins/builtin_pad
[libretro INFO] plugin: plugins/builtin_pad
[libretro INFO] Plugins loaded.
[libretro INFO] Error opening CD-ROM plugin!
[libretro INFO] failed to open plugins
[ERROR] [CONTENT LOAD]: Failed to load content
[INFO] [Core]: Content ran for a total of: 00 hours, 00 minutes, 00 seconds.
[INFO] [Core]: Unloading core..
[INFO] [Core]: Unloading core symbols..
[INFO] [Core Options]: Saved core options file to "/opt/retropie/configs/all/retroarch-core-options.cfg"

**Comment by gameblabla** [comment] 2021-08-30 23:13
I can confirm the issue.
I initially thought it was caused by my patches, however they don't touch the CD reading code at all and it turns out this is a regression from https://github.com/libretro/pcsx_rearmed/commit/9361a5aa4fef73e06bc78b7c462eb28a7d12e3d0.
@embercold, if you care to take a look. : P

**Comment by gameblabla** [comment] 2021-09-25 11:29
This should be fixed as of https://github.com/libretro/pcsx_rearmed/commit/4f0c5e3fd702a35b7a2ebc22519f59bbae7b3008.
I tried it with Crash 2 and Ape Escape PAL and it works properly now.
Let me know if the problem appears again.

**Closed by gameblabla** 2021-09-25 11:29 UTC
