### ISSUE TITLE
CHD Support for PCSX ReARMed [$200] [BOUNTY]

### ISSUE THREAD

**Issue by bebess** [libretro/pcsx_rearmed#170] opened 2018-04-28 18:31 UTC
hello ,

it will be great to have the chd support for the psx system...
3do/pcfx/pcenginecd/tg16cd/segacd , they all have the chd support
it is the last system (with saturn) that don't have these option

is it possible ?
maybe start a bounty

**Comment by dankcushions** [comment] 2018-04-28 18:34
Duplicate of https://github.com/libretro/pcsx_rearmed/issues/137, which you already commented on...

**Comment by Yabuato** [comment] 2018-05-04 06:01
Let's start a freaking bounty for this,eveybody want this feature.

**Comment by fr500** [comment] 2018-05-28 04:06
started a bounty;
https://www.bountysource.com/issues/57712065-chd-support

also for reference, here is the mednafen psx code:
https://github.com/libretro/beetle-psx-libretro/commit/052a22cd8c9abb5ca7629cdf912f5a0d48396a9c

**Comment by rubenjavier** [comment] 2018-08-02 06:39
Bounty amount increased
please update the title and post it at the libretro channel to attract more users andmake some noise, trust me the arm/raspberry community wants this, we just need to make them notice it in their twitters accounts

**Comment by rubenjavier** [comment] 2018-08-02 09:35
@bebess thanks mate, 
maybe if the title reflects its for the ReARMed core it will be picked faster byt the libretro team, Im gonna write them and RetroPie Recalbox to reach more people

**Comment by bebess** [comment] 2018-08-02 09:48
everyone wants this chd update !

**Comment by rubenjavier** [comment] 2018-08-02 09:55
@bebess I know!!! ;)
 but since the title dont have "ReARMed" in it, its not easily found on google at first, and when I link to it, the link doesnt say its for the ReARMed core
Thanks in avance

**Comment by bebess** [comment] 2018-08-02 15:22
@rubenjavier done , sorry :)

**Comment by rubenjavier** [comment] 2018-08-02 16:47
@bebess dont worry ;)
we are already being retwitted by libretro :D
lets hope recalbox and retropie give us a hand too and we get enough backers to make this happen
Twice the PSX fun in the same space!!!

**Comment by bebess** [comment] 2018-08-02 19:43
hope some people will come here :)

**Comment by QuaiGoner** [comment] 2018-08-26 07:31
Still nothing?

**Comment by rubenjavier** [comment] 2018-08-27 16:01
only libretro retweeted the information of this bounty, neither recalbox nor retropie retweeted it, leaving the majority of the users that would want this oblivious to this bounty, maybe someone can pitch some more in the bounty and we ask them to retweet the new amount to attract more backers (and a fixer)

**Comment by NightmareSteam** [comment] 2018-08-29 23:04
The bounty amount is now $140 so the title should get updated.

**Comment by twinaphex** [comment] 2018-08-29 23:14
Awesome. It sucks we have to manually update the title and that the system doesnt' take care of that itself but I guess here it goes.

**Comment by twinaphex** [comment] 2018-08-29 23:15
Retweeted it -

https://twitter.com/libretro/status/1034942543664959488

**Comment by twinaphex** [comment] 2018-08-29 23:17
Posted it here too -

https://www.reddit.com/r/RetroArch/comments/9bebhv/pcsx_rearmed_chd_bounty_increased_to_140/

and on Facebook as well.

It would be a good show of solidarity if recalbox and retropie would retweet this as well.

**Comment by rubenjavier** [comment] 2018-08-29 23:39
@twinaphex thank you so much, this is awesome
I hope recalbox and retropie give is a hand to reach more users interested in this.

**Comment by bebess** [comment] 2018-08-30 09:26
omg very good bounty update ! (and thanks to change the title :) )

**Comment by resurface** [comment] 2018-09-17 19:34
This seems doable, so I'll take the job. This'll probably require writing a CD plugin like cdrcimg using the [chdr](https://github.com/rtissera/libchdr) library. I'll need to do some experiments with CD audio and libcrypt copy protection support, so it can take a while. Expect first results sometime this Saturday.

**Comment by rubenjavier** [comment] 2018-09-17 19:49
@resurface That sounds amazing, thank you for your interest, looking forward to see you succeed!

**Comment by rubenjavier** [comment] 2018-10-04 16:36
Hello @resurface 
any news on the experiments?, thanks mate

**Comment by GregoryMcGregerson** [comment] 2018-10-06 18:16
I added $25 to the bounty. Good luck Mr. Resurface

**Comment by bebess** [comment] 2018-10-06 20:18
good to see some experiments here :)
(title changed with new bounty)

**Comment by NightmareSteam** [comment] 2018-11-21 02:07
Bounty is now at $185

**Comment by bebess** [comment] 2018-11-21 20:16
good :)
any news @resurface ?

**Comment by rubenjavier** [comment] 2019-03-13 19:54
> Posted it here too -
> 
> https://www.reddit.com/r/RetroArch/comments/9bebhv/pcsx_rearmed_chd_bounty_increased_to_140/
> 
> and on Facebook as well.
> 
> It would be a good show of solidarity if recalbox and retropie would retweet this as well.

@twinaphex hello mate, we haven't heard anything from the possible developer in six months.
Could you please repost this on twitter and facebook with the new amount to get some awareness, since Beetle dynamic recompiler seems froze too right now, this still looks like a great option on ARM hardware
Maybe @rtissera could be interested on the bounty to add another core to his list
Thanks in advance mate

**Comment by rubenjavier** [comment] 2019-03-14 17:18
@bebess sorry to Bother mate, could you update the title to the new amount, so it will show on the tweets and post?, thanks in advance

**Comment by bebess** [comment] 2019-03-15 18:36
updated :)

**Comment by aliaspider** [comment] 2019-05-14 12:29
CHD support has been merged. It would be cool if you could run some tests to see if it is working correctly.

**Comment by rubenjavier** [comment] 2019-05-14 13:06
@aliaspider
did you have a download link to a compiled version? I have a S912 arm box to try it
Thanks mate

**Comment by AnotherLife** [comment] 2019-05-14 23:01
Can you test Vib Ribbon(PAL)? My multi bin+cue files seem to work without issue. In CHD format it seems to be fine at first but when the first audio track ends there is some harbled/noise audio playing for 3-5 seconds until the next song plays. (When compressed to PBP the noise starts about 15-20 seconds into the first track.)

I tested it two times, no noise when the first song ends with cue+bin, a few seconds of noise on the CHD file.

Can you take a look at this, too? Pcsx seems to have problems accurately seeking to the right position? https://github.com/libretro/pcsx_rearmed/issues/233

**Comment by aliaspider** [comment] 2019-05-15 14:18
just pushed a fix for track information loading, could you check if this solves the issue you were having ?

**Comment by crazyrexz** [comment] 2019-05-16 02:01
question, it support chdv5 ?

and can you give me the tools for convert bin cue to chd?

 im really green in this feature. always using standart cue bin. tia

**Comment by AnotherLife** [comment] 2019-05-16 02:20
You need the tool called chdman.exe from the MAME package. And you run it from the command prompt like so:

chdman.exe createcd -i your.cue -o output.chd

Something like that.

Aliaspider I am waiting to be given a new build so I can test Vib Ribbon :/

**Comment by Yabuato** [comment] 2019-05-16 02:31
Any idea when will  Android core be updated? Can't wait to have a test.

**Comment by AnotherLife** [comment] 2019-05-16 13:55
> 
> 
> just pushed a fix for track information loading, could you check if this solves the issue you were having ?

I just test and it's the same. When the first song ends there are several seconds, maybe 4-7, of noise. It doesn't happen in the uncompressed bin+cue. I think Vib Ribbon (PAL) is a good game to test this on if you can get it.

**Comment by aliaspider** [comment] 2019-05-16 14:54
I did test the game and I'm not having this issue, are you sure you are on latest commit ?

**Comment by AnotherLife** [comment] 2019-05-16 17:21
Yes, I tested again, it plays about 8 seconds of a loud noise just as the words Round 2 appear and then the second song starts, I opened the menu and it says something like pcsx rearmed NEON 4b7520c at the bottom. And I did load the CHD file.

I am testing it on my PlayStation Classic with default options by the way.

I have checked my bin+cue against the redump info and they seem to match perfectly, both the cue contents and the bin checksums.

**Comment by gingerbeardman** [comment] 2019-05-16 23:12
I just tested the game I reported in #233 and the sound is still off. Infownloaded the nightly 5 hours ago.

**Comment by AnotherLife** [comment] 2019-05-17 01:32
Yes, I think there should be an effort to fix the existing cd audio bug seeking error, or whatever it is.

**Comment by aliaspider** [comment] 2019-05-17 08:26
can you please stop derailing this thread? this is about proper CHD support on pcsx_rearmed and not about #233

**Comment by gingerbeardman** [comment] 2019-05-17 10:07
> just pushed a fix for track information loading, could you check if this solves the issue you were having ?

I was answering this question. This isn't solved for me. HTH

**Comment by rubenjavier** [comment] 2019-05-17 11:42
@gingerbeardman seems to me that you want @aliaspider to fix a PCSX ReARMed bug not related to CHD support, but that obviously showcases when playing something in CHD, that is not the goal of this bounty. When that bug gets fixed on its own right, it will also play ok in CHD format.

We should be testing Disc that works on regular PCSX ReARMed and checking that the behaviour is the same in CHD format, no more.

**Comment by gingerbeardman** [comment] 2019-05-17 12:53
As I said, I was answering the above question. That's all.

**Comment by aliaspider** [comment] 2019-05-17 13:23
the fix was for the noise issue @AnotherLife  mentioned at the end of an audio track in the game he tested (Vib Ribbon(PAL)) compared to correct playback when using .bin/.cue, which I assume is related to the incorrect loading of track info in the first commit.

**Comment by gingerbeardman** [comment] 2019-05-17 16:12
Back to my Mac and my freshly made CHD files will not load in today's latest macOS nightly?
http://buildbot.libretro.com/nightly/apple/osx/x86_64/2019-05-17_RetroArch.dmg

Am I missing something? Eager to help.

**Comment by fr500** [comment] 2019-05-20 04:58
It doesn't seem to work on android for me.
I tried the same CHDs on windows and android. On android I just get "failed to load content"

**Comment by gingerbeardman** [comment] 2019-05-20 16:24
@fr500 same issue as me, directly above

**Comment by crazyrexz** [comment] 2019-05-25 14:10
yup everything is good thanks :)

just information for some newcomer like me , if you cant detect chd on retroarch, simply go to online update and choose update core information. im looking for the chd at the time update core but not find the file, and tinkering myself. voila it shows haha

**Comment by gingerbeardman** [comment] 2019-05-26 14:35
Still not working on macOS for me?

- http://buildbot.libretro.com/nightly/apple/osx/x86_64/2019-05-26_RetroArch.dmg
- Latest core downloads from Core Updater
- CHD created using `chdman` 0.209 (mame0209)
- CHD files work in Beetle

log 
[log.txt](https://github.com/libretro/pcsx_rearmed/files/3220404/log.txt)

**Comment by hizzlekizzle** [comment] 2020-04-24 21:59
It's been a year now and this seems to be working pretty well. I'm gonna go ahead and close this one out.

**Closed by hizzlekizzle** 2020-04-24 21:59 UTC

**Comment by gingerbeardman** [comment] 2020-04-25 07:00
@hizzlekizzle can you confirm the issue directly above is fixed on macOS?

**Comment by gingerbeardman** [comment] 2020-04-25 10:21
Above issue https://github.com/libretro/pcsx_rearmed/issues/170#issuecomment-496005461 could be related to https://github.com/libretro/pcsx_rearmed/issues/385
