### ISSUE TITLE
[3DS cia] Tekken and Wipeout : no music played

### ISSUE THREAD

**Issue by fraf** [libretro/pcsx_rearmed#201] opened 2018-10-06 00:32 UTC
Hi,

All in title.
Same problem with epsxe
But not with pSX_1_13. So the problem is not the iso.
Tested with retroarch 1.7.5 latest version.

Cheers

**Comment by Loquo** [comment] 2018-11-11 08:32
I have Tekken, and I have music when playing. ¿What kind of ISO are you using? Keep in mind that most of first PSX games are MULTITRACK (Tekken, Tomb Raider,...). If you only use the first track, you have the game but not the music. Multitrack iso has it's particular way to get ran.

**Comment by fraf** [comment] 2018-12-05 18:34
I'am talking about 3DS version built as cia wrapper.

**Comment by gingerbeardman** [comment] 2019-03-02 22:45
I have filed a dupe of this with more information #224

**Comment by retro-wertz** [comment] 2019-03-12 00:42
assuming cd-image is verified and uses cdaudio tracks and game is loaded using cue/toc/ccd etc and not directly the bin/img binary, it should work now as expected.

pushed a commit with fixes this (tested with vib-ribbon but on linux), hopefully 3ds users can confirm.

there was also a build problem with 3ds and the last available in buildbot was from 2018. its has also been fixed.

**Comment by fraf** [comment] 2019-03-12 06:01
There IS a duplicate : https://github.com/notaz/pcsx_rearmed/issues/111#issuecomment-468968252

Thanks for the fix.

PS: for epsxe, it depends of the right selected bios but music cd tracks works also.

**Comment by retro-wertz** [comment] 2019-03-12 06:07
thanks for confirmation

**Comment by gingerbeardman** [comment] 2019-03-12 15:12
I'll test this on 3DS asap

**Closed** 2023-10-18 22:54 UTC
